"""Initial migration

Revision ID: b1ed16e7ae8f
Revises: None
Create Date: 2026-07-30 14:46:48.165874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.models.user


# revision identifiers, used by Alembic.
revision: str = 'b1ed16e7ae8f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('profile_image', sa.String(length=500), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', 'PREFER_NOT_TO_SAY', name='gender'), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('address_line_1', sa.String(length=255), nullable=True),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('public_profile', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', app.models.user.GUID(), nullable=False),
    sa.Column('login_type', sa.Enum('EMAIL', 'PHONE', 'GOOGLE', name='logintype'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('device', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_history_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_history'))
    )
    op.create_index(op.f('ix_login_history_created_at'), 'login_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('opportunities',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_logo', sa.String(length=500), nullable=True),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('mode', sa.Enum('ONLINE', 'OFFLINE', 'HYBRID', name='opportunitymode'), nullable=False),
    sa.Column('type', sa.Enum('INTERNSHIP', 'JOB', 'VOLUNTEERING', 'EVENT', 'SCHOLARSHIP', 'COURSE', name='opportunitytype'), nullable=False),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.Column('skills_required', sa.String(length=500), nullable=True),
    sa.Column('application_link', sa.String(length=500), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('registration_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CLOSED', name='opportunitystatus'), nullable=False),
    sa.Column('featured', sa.Boolean(), nullable=False),
    sa.Column('banner_image', sa.String(length=500), nullable=True),
    sa.Column('created_by', app.models.user.GUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_opportunities_created_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_opportunities'))
    )
    op.create_index(op.f('ix_opportunities_category'), 'opportunities', ['category'], unique=False)
    op.create_index(op.f('ix_opportunities_created_at'), 'opportunities', ['created_at'], unique=False)
    op.create_index(op.f('ix_opportunities_featured'), 'opportunities', ['featured'], unique=False)
    op.create_index(op.f('ix_opportunities_organization_name'), 'opportunities', ['organization_name'], unique=False)
    op.create_index(op.f('ix_opportunities_slug'), 'opportunities', ['slug'], unique=True)
    op.create_index(op.f('ix_opportunities_status'), 'opportunities', ['status'], unique=False)
    op.create_index(op.f('ix_opportunities_title'), 'opportunities', ['title'], unique=False)
    op.create_table('otp_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', app.models.user.GUID(), nullable=True),
    sa.Column('user_identifier', sa.String(length=255), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('otp_type', sa.Enum('EMAIL', 'PHONE', name='otptype'), nullable=False),
    sa.Column('purpose', sa.Enum('LOGIN', 'REGISTER', 'PASSWORD_RESET', name='otppurpose'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otp_requests_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_requests'))
    )
    op.create_index(op.f('ix_otp_requests_created_at'), 'otp_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_otp_requests_user_id'), 'otp_requests', ['user_id'], unique=False)
    op.create_index(op.f('ix_otp_requests_user_identifier'), 'otp_requests', ['user_identifier'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', app.models.user.GUID(), nullable=False),
    sa.Column('user_id', app.models.user.GUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('operating_system', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    op.create_index(op.f('ix_user_sessions_created_at'), 'user_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_sessions_is_active'), 'user_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_sessions_refresh_token_hash'), 'user_sessions', ['refresh_token_hash'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_refresh_token_hash'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_is_active'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_created_at'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_otp_requests_user_identifier'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_user_id'), table_name='otp_requests')
    op.drop_index(op.f('ix_otp_requests_created_at'), table_name='otp_requests')
    op.drop_table('otp_requests')
    op.drop_index(op.f('ix_opportunities_title'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_status'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_slug'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_organization_name'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_featured'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_created_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_category'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_index(op.f('ix_login_history_created_at'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
